import { BasePackage } from "@/types";

export const packagesData: BasePackage[] = [
  {
    slug: "dubai-classic-6d",
    title: "Dubai & Abu Dhabi Classic Tour",
    description: "Experience 6 days in Dubai and Abu Dhabi featuring Burj Khalifa 124th floor access, a 2-hour glass yacht dinner cruise, VIP 4x4 desert safari, complimentary limousine ride, and La Mer beach visit.",
    status: "PUBLISHED",
    category: "International",
    isFeatured: true,
    flyerHref: "/flyers/dubai-classic-6d.pdf",
    duration: { nights: 5, days: 6 },
    destinations: ["Dubai", "Abu Dhabi"]
  },
  // {
  //   slug: "dubai-abu-dhabi-yas-island",
  //   title: "Dubai, Abu Dhabi & Yas Island Theme Park Experience",
  //   description: "The ultimate 6-day UAE adventure featuring Burj Khalifa, luxury glass yacht dinner, 4x4 VIP desert safari with live shows, a overnight stay on Yas Island with Theme Park access, and Abu Dhabi BAPS Temple visit.",
  //   status: "PUBLISHED",
  //   category: "International",
  //   isFeatured: true,
  //   flyerHref: "/flyers/dubai-yas-island.pdf",
  //   duration: { nights: 5, days: 6 },
  //   destinations: ["Dubai", "Abu Dhabi", "Yas Island"]
  // },
  {
    slug: "dubai-abu-dhabi-yas-island",
    title: "Dubai & Abu Dhabi Yas Island Experience",
    description: "Experience the luxury of Dubai and Abu Dhabi featuring 124th-floor Burj Khalifa access, a private yacht dinner, VIP desert safari, and Theme Park adventures at Yas Island.",
    destinations: ["Dubai", "Abu Dhabi", "Yas Island"],
    duration: { nights: 5, days: 6 },
    isFeatured: true,
    category: "International",
    status: "PUBLISHED",
    flyerHref: "https://drive.google.com/file/d/1v49ktDsoSqtaF1h1aUgggniEJdSCn9UG/view?usp=drive_link",
  },
  {
    slug: "singapore-malaysia-7d",
    title: "Singapore & Malaysia Highlights",
    description: "Explore the best of Singapore and Malaysia with visits to Universal Studios, Gardens by the Bay, Sentosa Island, Genting Highlands, and Kuala Lumpur city attractions.",
    destinations: ["Singapore", "Kuala Lumpur", "Genting Highlands"],
    duration: { nights: 6, days: 7 },
    isFeatured: true,
    category: "International",
    status: "PUBLISHED",
    flyerHref: "https://drive.google.com/file/d/1vVlebwevZ4lk5fJzJ3RJGzBV0Xxb4Jln/view?usp=drive_link",
  },
  {
    slug: "singapore-malaysia-thailand-11d",
    title: "Singapore, Malaysia & Thailand Trio",
    description: "An extensive 11-day multi-country tour covering Singapore, Malaysia, Bangkok, and Pattaya with theme parks, island tours, and cultural highlights.",
    destinations: ["Singapore", "Kuala Lumpur", "Genting Highlands", "Bangkok", "Pattaya"],
    duration: { nights: 10, days: 11 },
    isFeatured: false,
    category: "International",
    status: "PUBLISHED",
    flyerHref: "https://drive.google.com/file/d/1u5qgbU8wFy8VzOKgCaahYfmLza_fU8LP/view?usp=drive_link",
  },
  {
    slug: "singapore-malaysia-cruise-9d",
    title: "Singapore & Malaysia with Resort World Cruise",
    description: "Enjoy a 9-day luxury vacation incorporating 2 nights on the Resort World Cruise alongside stays in Singapore and Kuala Lumpur.",
    destinations: ["Singapore", "Resort World Cruise", "Kuala Lumpur", "Genting Highlands"],
    duration: { nights: 8, days: 9 },
    isFeatured: true,
    category: "International",
    status: "PUBLISHED",
    flyerHref: "https://drive.google.com/file/d/1yrdbtnBN8HQHHftc6tbk-GrXatGaxOs7/view?usp=drive_link",
  },
  {
    slug: "singapore-malaysia-thailand-cruise-13d",
    title: "Ultimate Southeast Asia: Singapore, Malaysia, Thailand & Cruise",
    description: "The complete 13-day Southeast Asian trip featuring Singapore, a 2-night cruise, Kuala Lumpur, Pattaya, and Bangkok.",
    destinations: ["Singapore", "Resort World Cruise", "Kuala Lumpur", "Bangkok", "Pattaya"],
    duration: { nights: 12, days: 13 },
    isFeatured: false,
    category: "International",
    status: "PUBLISHED",
    flyerHref: "https://drive.google.com/file/d/1OSxTIjR8-EtBvVwcTfkzgW7VBK2HYpB_/view?usp=drive_link",
  },
  {
    slug: "vietnam-signature-9d",
    title: "Signature Vietnam: Hanoi, Halong Bay, Da Nang & Phu Quoc",
    description: "An incredible 9-day journey across Vietnam featuring an overnight Halong Bay luxury cruise, Ba Na Hills Golden Bridge, and Phu Quoc Island.",
    destinations: ["Hanoi", "Halong Bay", "Da Nang", "Phu Quoc Island"],
    duration: { nights: 8, days: 9 },
    isFeatured: false,
    category: "International",
    status: "PUBLISHED",
    flyerHref: "https://drive.google.com/file/d/1UK_Vr5XvsKoBE97ZCguEzr3JBq0f0aQA/view?usp=drive_link",
  },
  {
    slug: "phuket-krabi-escape",
    title: "Phuket & Krabi Island Hopping",
    description: "Relax on pristine Thai beaches with speedboat tours to Phi Phi Islands and James Bond Island.",
    destinations: ["Phuket", "Krabi", "Phi Phi Islands"],
    category: "International",
    duration: { nights: 5, days: 6 },
    isFeatured: false,
    status: "PUBLISHED",
  },
  {
    slug: "goa-beach-bliss",
    title: "Vibrant Goa Beach & Nightlife Tour",
    description: "Unwind on the sandy shores of Goa with river cruises, water sports, and heritage church visits.",
    destinations: ["North Goa", "South Goa"],
    category: "Domestic",
    duration: { nights: 3, days: 4 },
    isFeatured: true,
    status: "PUBLISHED",
  },
  {
    slug: "kerala-backwaters-munnar",
    title: "Enchanting Kerala Houseboat & Hill Station",
    description: "Immerse yourself in God's Own Country with tea gardens in Munnar and an overnight backwater houseboat cruise in Alleppey.",
    destinations: ["Munnar", "Thekkady", "Alleppey Houseboat", "Kochi"],
    category: "Domestic",
    duration: { nights: 5, days: 6 },
    isFeatured: true,
    status: "PUBLISHED",
    flyerHref: "https://drive.google.com/file/d/1rbrz3qiOuFqG2n6wpJuW3_xoE2xmU6cO/view?usp=drive_link",
  },
  {
    slug: "shimla-mandi-manali",
    title: "Scenic Himachal: Shimla, Mandi & Manali",
    description: "Travel through snow-capped mountains, Solang Valley adventure parks, and pine valleys in Himachal Pradesh.",
    destinations: ["Shimla", "Mandi", "Manali", "Kullu"],
    category: "Domestic",
    duration: { nights: 6, days: 7 },
    isFeatured: false,
    status: "PUBLISHED",
  },
  {
    slug: "royal-udaipur-customize",
    title: "Royal Udaipur & Mount Abu Custom Tour",
    description: "Experience royal Rajasthani heritage with Lake Pichola boat rides, majestic palaces, and hill station scenery in Mount Abu.",
    destinations: ["Udaipur", "Mount Abu"],
    category: "Domestic",
    duration: { nights: 3, days: 4 },
    isFeatured: false,
    status: "PUBLISHED",
  },
  {
    slug: "sikkim-gangtok-darjeeling",
    title: "Sikkim & Darjeeling Himalayan Magic",
    description: "Journey through the Eastern Himalayas visiting Gangtok monasteries, Tsomgo Lake, and Tiger Hill sunrise point in Darjeeling.",
    destinations: ["Gangtok", "Tsomgo Lake", "Darjeeling"],
    category: "Domestic",
    duration: { nights: 5, days: 6 },
    isFeatured: false,
    status: "PUBLISHED",
  }
];